name: Deployment Workflow

on:
  push:
    branches:
      - staging  # Assuming you want to trigger this on pushes to the main branch
jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'  # Only run this job on the staging branch

    steps:
      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: test echo
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        run: |
          echo "key : $AWS_ACCESS_KEY_ID"

      - name: set sls creds
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        run: serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      
      - name: Deploy to Staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        run: |
          cd ..
          sls deploy --stage dev
